---
name: Java CI with Maven
on:
#   schedule:
#     - cron: 0 0 * * *
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      Env:
        description: Environment to run
        default: dev
        required: true

      tags:
      description: tags to use
      default: "@All"
      required: true
  
jobs:
  call-automation:
    uses: firecloudfelblood/pythonInJava/.github/workflows/maven.yml@master
  build:
    runs-on: ubuntu-latest
    env:
      ENV: dev
    steps:
#      - name: running another repo
#        uses: peter-evans/repository-dispatch@v2
##      - name: running another repo
##        uses: peter-evans/repository-dispatch@v2
#
#        with:
#          token: ${{secrets.ACCESS_TOKEN}}
#          repository: felbloodfirecloud/pythonInJava
#          event-type: my-event
#          client-payload: '{"githuB": ${{ toJson(github) }}}'
        
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: maven
      - name: run test with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/java/testng.xml
        
      - name:  Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: target/surefire-reports
          
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: target/surefire-reports
    
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: target/surefire-reports/*.xml    # Path to test results
          reporter: jest-juni
        
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6


