---
name: Java CI with Maven
on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
      - feature/reporter
      - feature/testngmigration
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: dev
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: maven

      - name: update apt-get
        run:  echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        
      - name: Pre install cli
        run: sudo apt-get install apt-transport-https ca-certificates gnupg

      - name: Install cli
        run: sudo apt-get update && sudo apt-get install google-cloud-cli

      - name: Initialize Cli
        run: gcloud init

      - name: run test with Maven
        run: mvn clean test -DsuiteXmlFile=testng.xml




