---
name: Java CI with Maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: maven
      - name: run test with Maven
        run: mvn clean test verify
      - name: Cucumber Report to Annotations
        uses: deblockt/cucumber-report-annotations-action@v1.11
        with:
          access-token: ${{ secrets.BUILD_KEY3}}
          path: ./Reports/CalanticJSonReport.json

      
