---
name: Java CI with Maven
on:
#   schedule:
#     - cron: 0 0 * * *
  push:
    branches:
      - main
      - feature/cucumber_report
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: maven
      - name: run test with Maven
        run: mvn clean test #-Dsurefire.suiteXmlFiles=src/test/java/testng.xml
        
      - name:  Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: target/surefire-reports
          
      - name: Cucumber Report to Annotations
        uses: deblockt/cucumber-report-annotations-action@v1.11
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path:  "./Reports/cucumber.json"
          
