---
name: Java CI with Maven
on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
      - feature/reporter
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: dev
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: maven
      - name: run test with Maven
        run: mvn -e -X clean test verify
        
      - name:  Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: ./Reports
          
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: Reports/
          
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: Reports/*.xml    # Path to test results
          reporter: jest-junit

      - name: Checkout repository
        uses: actions/checkout@v3

            # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
                # If you wish to specify custom queries, you can do so here or in a config file.
                # By default, queries listed here will override any specified in a config file.
                # Prefix the list here with "+" to use these queries and those in the config file.
                # queries: ./path/to/local/query, your-org/your-repo/queries@main

            # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
            # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

            # ℹ️ Command-line programs to run using the OS shell.
            # 📚 https://git.io/JvXDl

            # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
            #    and modify them (or add more) to build your code if your project
            #    uses a compiled language

            #- run: |
            #   make bootstrap
            #   make release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6


